name: WebView Builder
on:
  repository_dispatch:
    types: [build_apk]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu GitHub'dan Çek
        uses: actions/checkout@v4

      - name: Java JDK 17 Kurulumu
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Gradelw Yetkisini Düzenle
        run: chmod +x gradlew

      - name: Uygulama Bilgilerini Güncelle (Placeholder Değişimi)
        run: |
          sed -i "s|APP_URL_PLACEHOLDER|${{ github.event.client_payload.url }}|g" app/src/main/java/mgks/os/swv/SWVContext.java
          sed -i "s|APP_NAME_PLACEHOLDER|${{ github.event.client_payload.name }}|g" app/src/main/res/values/strings.xml

      - name: APK Derleme (Build)
        run: ./gradlew assembleDebug

      - name: APK Dosyasını Kaydet (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.client_payload.name }}-WebView-App
          path: app/build/outputs/apk/debug/*.apk
