name: Gorizyon Builder v8

on:
  repository_dispatch:
    types: [aswv_build] # PHP tarafındaki event_type ile aynı olduğundan emin ol

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu GitHub'dan Çek
        uses: actions/checkout@v4

      - name: Java JDK 17 Kurulumu
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Gradelw Yetkisini Düzenle
        run: chmod +x gradlew

      - name: swv.properties Güncelle (Nokta Atışı)
        run: |
          # URL Güncelleme
          sed -i "s|^app.url=.*|app.url=${{ github.event.client_payload.app_url }}|g" swv.properties
          
          # Uygulama İsmi Güncelleme (Strings.xml)
          sed -i "s|APP_NAME_PLACEHOLDER|${{ github.event.client_payload.app_name }}|g" app/src/main/res/values/strings.xml
          
          # User Agent Postfix Güncelleme (İsteğe bağlı)
          sed -i "s|^agent.postfix.value=.*|agent.postfix.value=Gorizyon-${{ github.event.client_payload.app_name }}|g" swv.properties

      - name: APK Derleme (Build)
        run: ./gradlew assembleDebug

      - name: APK Dosyasını Sunucuya Geri Gönder (Callback)
        run: |
          curl -X POST \
          -F "file=@app/build/outputs/apk/debug/app-debug.apk" \
          -F "build_id=${{ github.event.client_payload.app_id }}" \
          "https://gorizyon.com.tr/builder/callback.php?token=${{ secrets.CALLBACK_TOKEN }}"
          
