name: Gorizyon Builder Engine v8

on:
  repository_dispatch:
    # worker.php'den gelen event_type ile birebir eşleşti
    types: [aswv_build]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu GitHub'dan Çek
        uses: actions/checkout@v4

      - name: Java JDK 17 Kurulumu
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Gradelw Yetkisini Düzenle
        run: chmod +x gradlew

      - name: swv.properties ve Strings Güncelle
        run: |
          # PHP'den (worker.php) gelen app_url ve app_name verilerini kullanıyoruz
          sed -i "s|^app.url=.*|app.url=${{ github.event.client_payload.app_url }}|g" swv.properties
          
          # Strings.xml içindeki APP_NAME_PLACEHOLDER'ı değiştirir
          sed -i "s|APP_NAME_PLACEHOLDER|${{ github.event.client_payload.app_name }}|g" app/src/main/res/values/strings.xml

      - name: APK Derleme (Build)
        run: ./gradlew assembleDebug

      - name: APK Dosyasını Sunucuya Geri Gönder
        run: |
          curl -X POST \
          -F "file=@app/build/outputs/apk/debug/app-debug.apk" \
          -F "build_id=${{ github.event.client_payload.app_id }}" \
          "https://gorizyon.com.tr/builder/callback.php?token=${{ secrets.CALLBACK_TOKEN }}"

      - name: APK Dosyasını Sunucuya Geri Gönder (Callback)
        run: |
          curl -X POST \
          -F "file=@app/build/outputs/apk/debug/app-debug.apk" \
          -F "build_id=${{ github.event.client_payload.app_id }}" \
          "https://gorizyon.com.tr/builder/callback.php?token=${{ secrets.CALLBACK_TOKEN }}"
          
